namespace: massopencloud
name: osac
version: 0.1.0
readme: README.md
authors: [Mass Open Cloud]
description: Mass Open Cloud ESI integration for OSAC
license_file: LICENSE
tags: [osac, cloud, baremetal, esi]
